apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-scheduler
    image: quay.io/coreos/hyperkube:v${K8S_VERSION}
    command:
    - /hyperkube
    - scheduler
    - --master=http://${MASTER_HOST}:8080
    - --leader-elect=true
    resources:
      requests:
        cpu: 100m
    livenessProbe:
      httpGet:
        host: ${MASTER_HOST}
        path: /healthz
        port: 10251
      initialDelaySeconds: 15
      timeoutSeconds: 15
